// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9w4G-9in-GzGGs9sEetXvz8h4NXtNxVU',
    appId: '1:246255479274:web:32a8b3b80a82c59d862a93',
    messagingSenderId: '246255479274',
    projectId: 'starpage-ed409',
    authDomain: 'starpage-ed409.firebaseapp.com',
    databaseURL: 'https://starpage-ed409-default-rtdb.firebaseio.com',
    storageBucket: 'starpage-ed409.firebasestorage.app',
    measurementId: 'G-9MN1THB5Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIylfRJaAtpXSuMtoeKUzJbYEScdAGGhY',
    appId: '1:246255479274:android:341fbd17995cbd2e862a93',
    messagingSenderId: '246255479274',
    projectId: 'starpage-ed409',
    databaseURL: 'https://starpage-ed409-default-rtdb.firebaseio.com',
    storageBucket: 'starpage-ed409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcne8lCBS7X5FXGPC8CksGdHyFnUbEsM4',
    appId: '1:246255479274:ios:b2795341afca41b6862a93',
    messagingSenderId: '246255479274',
    projectId: 'starpage-ed409',
    databaseURL: 'https://starpage-ed409-default-rtdb.firebaseio.com',
    storageBucket: 'starpage-ed409.firebasestorage.app',
    iosBundleId: 'com.example.flutterStarsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcne8lCBS7X5FXGPC8CksGdHyFnUbEsM4',
    appId: '1:246255479274:ios:b2795341afca41b6862a93',
    messagingSenderId: '246255479274',
    projectId: 'starpage-ed409',
    databaseURL: 'https://starpage-ed409-default-rtdb.firebaseio.com',
    storageBucket: 'starpage-ed409.firebasestorage.app',
    iosBundleId: 'com.example.flutterStarsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9w4G-9in-GzGGs9sEetXvz8h4NXtNxVU',
    appId: '1:246255479274:web:6cc6cd1ae9d67bb4862a93',
    messagingSenderId: '246255479274',
    projectId: 'starpage-ed409',
    authDomain: 'starpage-ed409.firebaseapp.com',
    databaseURL: 'https://starpage-ed409-default-rtdb.firebaseio.com',
    storageBucket: 'starpage-ed409.firebasestorage.app',
    measurementId: 'G-ZYEZKWVQBT',
  );
}
